name: RealVillagerTowns
version: '${version}'
main: io.github.tanguygab.realvillagertowns.RealVillagerTowns
depend: [LibsDisguises]
authors: [Eliminator,Tanguygab]
api-version: 1.13

commands:
  realvillagertowns:
    aliases: [rvt]
    description: Base mca command.
    usage: /<command>
    default: true
  bringkids:
    aliases: [kids]
    description: Bring your kids to you.
    usage: /<command>
    default: true